[theme]
base = "light"
primaryColor = "#D90000"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212529"
font = "sans serif"

[server]
port = 8501
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
